name: Setup Expo Android Credentials

on:
  workflow_dispatch: # запуск вручную

jobs:
  setup-creds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Expo CLI
        run: npm install -g eas-cli

      - name: Configure Android credentials
        run: eas credentials -p android --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
