name: Build Expo Android App

on:
  workflow_dispatch: # Можно запускать вручную

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # Проверяем код из репозитория
      - uses: actions/checkout@v3

      # Настройка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Установка EAS CLI
      - name: Install Expo CLI
        run: npm install -g eas-cli

      # Собираем Android APK/AAB используя существующий keystore
      - name: Build Android APK
        run: |
          eas build \
            --platform android \
            --profile production \
            --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
